// import { ProtectedPurchaseRequest } from '@/utils/functions/ProtectedRoutesForRole/ProtectedPurchaseRequest';
// import {
//   Dashboard,
//   PurchaseRequest,
//   Article,
//   ExistingArticle,
//   Category,
//   SubCategory,
//   ProvidersView,
//   WarehouseView,
//   PurchaseAuthorizationView,
//   PurchaseConfigView,
//   AccountView,
//   WarehouseSelected,
//   PointOfSaleView,
//   PackageCatalogueView,
//   PharmacyConfigView,
//   SellsHistoryView,
//   PointOfSaleCheckoutView,
//   ReceiptEmitterView,
//   ConfigEmitterUsersView,
//   CloseCheckoutHistoryView,
//   CloseCheckoutView,
//   ProgrammingRegisterView,
//   PatientsEntryView,
//   RoomsView,
//   SurgeryProcedureView,
//   ProgrammingCalendarView,
//   // ConfigurationProgrammingView,
//   ProgrammingRequestView,
//   //BiomedicalEquipmentView,
//   AnesthesiologistView,
//   XRayView,
//   MedicView,
//   NurseRequestView,
//   MedicalShiftView,
//   // AnesthesiologistShiftView,
//   OperatingRoomView,
//   TypesRoomView,
//   DailyOperatingView,
//   XRayRequestView,
//   XRayRequestManagementView,
//   // HospitalizationConfigView,
//   RecoveryRoomsView,
//   HospitalRoomsView,
//   AssignedRoomsView,
//   HospitalRoomsCalendarView,
//   RequestsConfigView,
//   InvoiceView,
//   OutstandingBillsView,
//   OperatingPackagesView,
//   MedicalConsultationView,
//   PatientKardexView,
//   CheckoutReportView,
// } from '../utils/LazyRoutes';
// import { ProtectedRouteSupply } from '@/utils/functions/ProtectedRoutesForRole/ProtectedRouteSupply';

// export const purchasesRoutes = [
//   {
//     title: 'Compras',
//     path: 'compras',
//     protected: <ProtectedPurchaseRequest />,
//     children: [
//       {
//         path: 'solicitud-compras',
//         element: <PurchaseRequest />,
//       },
//     ],
//   },
//   {
//     path: 'compras',
//     protected: <ProtectedRouteSupply />,
//   },
// ];
